version: '3'

tasks:
  full-switch:
    cmds:
      - task: nixos-switch
      - task: home-manager-switch

  format:
    desc: "Format all Nix files"
    cmds:
      - nix-shell -p nixpkgs-fmt --run "find . -name '*.nix' -not -path './.git/*' | xargs nixpkgs-fmt"

  nixos-switch:
    cmds:
      - cmd: sudo nixos-rebuild switch --flake 'path:.'
        platforms: [linux]
      - cmd: sudo nix --extra-experimental-features nix-command --extra-experimental-features flakes run nix-darwin -- switch --flake 'path:.'
        platforms: [darwin]

  home-manager-switch:
    cmds:
      - home-manager switch --flake 'path:.'

  flake-update:
    cmds:
      - nix flake update

  pre-commit-install:
    desc: "Install pre-commit hooks"
    cmds:
      - nix-shell -p pre-commit --run "pre-commit install"

  pre-commit-run:
    desc: "Run pre-commit hooks on all files"
    cmds:
      - nix-shell -p pre-commit --run "pre-commit run --all-files"
