version: '3'

tasks:
  nixos-switch:
    cmds:
      - cmd: sudo nixos-rebuild switch --flake 'path:.'
        platforms: [linux]
      - cmd: sudo darwin-rebuild switch --flake 'path:.'
        platforms: [darwin]

  format:
    desc: "Format all Nix files"
    cmds:
      - find . -name '*.nix' -not -path './.git/*' | xargs nixpkgs-fmt

  pre-commit-install:
    desc: "Install pre-commit hooks"
    cmds:
      - nix-shell -p pre-commit --run "pre-commit install"

  pre-commit-run:
    desc: "Run pre-commit hooks on all files"
    cmds:
      - nix-shell -p pre-commit --run "pre-commit run --all-files"
