version: '3'

tasks:
  full-switch:
    cmds:
      - sudo nixos-rebuild switch --flake '.'
      - home-manager switch --flake '.'
  nixos-switch:
    cmds:
      - sudo nixos-rebuild switch --flake '.'
  home-manager-switch:
    cmds:
      - home-manager switch --flake '.'
  flake-update:
    cmds:
      - nix flake update
